Version 0.7
Now supports RAR filetypes. There seems to be some quirkiness to them, however I do not know if it is the RAR files themselves or simply their location.
Quirky errors/bugs
PermissionError: [Errno 13] Permission denied:
 - Error is raised, but extraction still happens. It is being raised in certain directories, but not all. Works just find on test_folder directory ( located on Desktop ), but having issues with /Desktop/Raw Manga/Zips/コープスパーティー BloodCovered/
- This specifically is only affecting RAR extractions.

Possible bug with select_image_folder function. Also seems to be certain directories. test_image directory was fine, but it wouldn't work well with sub-subdirectories ( like the ones in the above directory ). Retested to get exact error, but it seems to work now? Further testing is needed. Only tested on

Trying to get .7z filetype support, but not having much success. Currently trying py7zr library. It looks like it will need to be separate from the .zip and .rar extraction function, but need to do more research.